--- 

- name: "Create {{ service_id }} directory"
  file:
    path: ~/{{ service_id }}
    state: directory

- ansible.posix.synchronize: 
    dest: ~/{{ service_id }}
    src: ../../../../../javatron/
