---
- name: Get latest packages info
  shell: "apt-get update -y"
  become: true

- name: Get install dependencies
  package:
    name: '{{ packages }}'
  vars:
    packages:
      - rsync
  become: yes
