name: WIP - Deployment tests

on: [push, pull_request, workflow_dispatch]

jobs:
  deployment-test:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        cloud_provider: [aws, azure, gcp] 
        scenario: [happy]

    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: pull v3 deployer image
        run: docker pull ghcr.io/newrelic/deployer:latest

      - name: general setup
        env:
          USER_CONFIG: ${{ secrets.UAT_USER_CONFIG }}
        run: |
          rm -rf configs demo-javatron tmp
          mkdir configs demo-javatron tmp
          cp ./user_acceptance_tests/deploy_configs/${{ matrix.scenario }}-${{ matrix.cloud_provider }}.deploy.config.json configs
          cp -R deploy demo-javatron
          cp -R javatron demo-javatron
          echo "$USER_CONFIG" > configs/javatron-testing.user.credentials.local.json
          bundle install --gemfile=user_acceptance_tests/tests/Gemfile

      - name: aws setup
        env:
          PEM_KEY: ${{ secrets.PEM_KEY }}
        run: |
          echo "$PEM_KEY" > configs/uat-ca.pem
          chmod 400 configs/uat-ca.pem

      - name: azure setup
        env:
          ID_RSA_PUB: ${{ secrets.UAT_AZURE_ID_RSA_PUB_FILE }}
          ID_RSA: ${{ secrets.UAT_AZURE_ID_RSA_FILE }}
        run: |
          ssh-keygen -m PEM -t rsa -b 4096 -f $HOME/.ssh/id_rsa -q -N ""
          mv $HOME/.ssh configs

      - name: gcp setup
        env:
          UAT_GCP_PEM_FILE: ${{ secrets.UAT_GCP_PEM_FILE }}
          UAT_GCP_SERVICEACCOUNT_FILE: ${{ secrets.UAT_GCP_SERVICEACCOUNT_FILE }}
        run: | 
          echo "$UAT_GCP_PEM_FILE" > $GITHUB_WORKSPACE/configs/compute-user.pem
          chmod 400 $GITHUB_WORKSPACE/configs/compute-user.pem
          echo "$UAT_GCP_SERVICEACCOUNT_FILE" > $GITHUB_WORKSPACE/configs/demo-newrelic-staging-gcp-service-account.json

      - name: debug ls - configs
        run: ls $GITHUB_WORKSPACE/configs

      - name: run deployment
        id: deployment
        run: |
          docker run -t \
          -v $GITHUB_WORKSPACE/demo-javatron:/mnt/deployer/demo-javatron \
          -v $GITHUB_WORKSPACE/configs:/mnt/deployer/configs \
          -v $GITHUB_WORKSPACE/tmp:/tmp \
          ghcr.io/newrelic/deployer:latest \
          main.rb -d /mnt/deployer/configs/${{ matrix.scenario }}-${{ matrix.cloud_provider }}.deploy.config.json -l debug

      - name: debug ls - tmp
        run: |
          ls tmp

      - name: run tests
        run: ruby ./user_acceptance_tests/tests/${{ matrix.scenario }}.rb
        env:
          TEST_INPUT_FILE_LOCATION: tmp/javatron-testing-${{ matrix.scenario }}-${{ matrix.cloud_provider }}/deploy_summary.txt

      - name: run teardown
        if: always()
        run: |
          docker run -t \
          -v $GITHUB_WORKSPACE/demo-javatron:/mnt/deployer/demo-javatron \
          -v $GITHUB_WORKSPACE/configs:/mnt/deployer/configs \
          -v $GITHUB_WORKSPACE/tmp:/tmp \
          ghcr.io/newrelic/deployer:latest \
          main.rb -d /mnt/deployer/configs/${{ matrix.scenario }}-${{ matrix.cloud_provider }}.deploy.config.json -t -l debug
      